const shapes = {
    box: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- box -->
    <g id="node1" class="node">
    <title>box</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    polygon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- polygon -->
    <g id="node1" class="node">
    <title>polygon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    ellipse: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- ellipse -->
    <g id="node1" class="node">
    <title>ellipse</title>
    <ellipse fill="#d3d3d3" stroke="#000000" cx="27" cy="-18" rx="27" ry="18"/>
    </g>
    </g>
    </svg>
    `,
    oval: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- oval -->
    <g id="node1" class="node">
    <title>oval</title>
    <ellipse fill="#d3d3d3" stroke="#000000" cx="27" cy="-18" rx="27" ry="18"/>
    </g>
    </g>
    </svg>
    `,
    circle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="44pt" height="44pt"
     viewBox="0.00 0.00 44.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 40,-40 40,4 -4,4"/>
    <!-- circle -->
    <g id="node1" class="node">
    <title>circle</title>
    <ellipse fill="#d3d3d3" stroke="#000000" cx="18" cy="-18" rx="18" ry="18"/>
    </g>
    </g>
    </svg>
    `,
    point: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="12pt" height="12pt"
     viewBox="0.00 0.00 11.60 11.60" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 7.6)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-7.6 7.6,-7.6 7.6,4 -4,4"/>
    <!-- point -->
    <g id="node1" class="node">
    <title>point</title>
    <ellipse fill="#000000" stroke="#000000" cx="1.8" cy="-1.8" rx="1.8" ry="1.8"/>
    </g>
    </g>
    </svg>
    `,
    egg: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="65pt" height="44pt"
     viewBox="0.00 0.00 65.49 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 61.4869,-40 61.4869,4 -4,4"/>
    <!-- egg -->
    <g id="node1" class="node">
    <title>egg</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="31.426,-.0493 33.202,-.1479 34.9597,-.2953 36.6919,-.4913 38.3915,-.7353 40.0517,-1.0266 41.666,-1.3645 43.2281,-1.7479 44.732,-2.1759 46.1722,-2.6472 47.5435,-3.1606 48.8411,-3.7147 50.0607,-4.308 51.1984,-4.9388 52.2508,-5.6054 53.2152,-6.3059 54.089,-7.0385 54.8704,-7.8012 55.558,-8.5918 56.151,-9.4082 56.6489,-10.2481 57.052,-11.1093 57.3606,-11.9894 57.5759,-12.886 57.6992,-13.7965 57.7324,-14.7186 57.6776,-15.6497 57.5374,-16.5873 57.3145,-17.5287 57.0121,-18.4713 56.6334,-19.4127 56.182,-20.3503 55.6616,-21.2814 55.0759,-22.2035 54.4287,-23.114 53.7241,-24.0106 52.966,-24.8907 52.1582,-25.7519 51.3048,-26.5918 50.4093,-27.4082 49.4757,-28.1988 48.5074,-28.9615 47.5078,-29.6941 46.4803,-30.3946 45.4278,-31.0612 44.3533,-31.692 43.2595,-32.2853 42.1488,-32.8394 41.0235,-33.3528 39.8858,-33.8241 38.7373,-34.2521 37.58,-34.6355 36.4152,-34.9734 35.2443,-35.2647 34.0685,-35.5087 32.8889,-35.7047 31.7065,-35.8521 30.522,-35.9507 29.3364,-36 28.1505,-36 26.9649,-35.9507 25.7804,-35.8521 24.598,-35.7047 23.4184,-35.5087 22.2426,-35.2647 21.0717,-34.9734 19.9069,-34.6355 18.7495,-34.2521 17.6011,-33.8241 16.4633,-33.3528 15.3381,-32.8394 14.2274,-32.2853 13.1335,-31.692 12.0591,-31.0612 11.0066,-30.3946 9.9791,-29.6941 8.9795,-28.9615 8.0112,-28.1988 7.0775,-27.4082 6.1821,-26.5918 5.3286,-25.7519 4.5209,-24.8907 3.7628,-24.0106 3.0582,-23.114 2.411,-22.2035 1.8253,-21.2814 1.3048,-20.3503 .8534,-19.4127 .4748,-18.4713 .1724,-17.5287 -.0505,-16.5873 -.1907,-15.6497 -.2455,-14.7186 -.2123,-13.7965 -.089,-12.886 .1263,-11.9894 .4349,-11.1093 .8379,-10.2481 1.3359,-9.4082 1.9289,-8.5918 2.6165,-7.8012 3.3979,-7.0385 4.2717,-6.3059 5.2361,-5.6054 6.2885,-4.9388 7.4262,-4.308 8.6458,-3.7147 9.9434,-3.1606 11.3147,-2.6472 12.7549,-2.1759 14.2588,-1.7479 15.8209,-1.3645 17.4352,-1.0266 19.0954,-.7353 20.795,-.4913 22.5271,-.2953 24.2848,-.1479 26.0609,-.0493 27.848,0 29.6389,0 31.426,-.0493"/>
    </g>
    </g>
    </svg>
    `,
    triangle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- triangle -->
    <g id="node1" class="node">
    <title>triangle</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="27,-36 0,-9 54,-9 27,-36"/>
    </g>
    </g>
    </svg>
    `,
    none: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- none -->
    <g id="node1" class="node">
    <title>none</title>
    <polygon fill="#d3d3d3" stroke="transparent" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    plaintext: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- plaintext -->
    <g id="node1" class="node">
    <title>plaintext</title>
    <polygon fill="#d3d3d3" stroke="transparent" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    plain: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="8pt" height="8pt"
     viewBox="0.00 0.00 8.00 8.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 4)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-4 4,-4 4,4 -4,4"/>
    <!-- plain -->
    <g id="node1" class="node">
    <title>plain</title>
    <polygon fill="#d3d3d3" stroke="transparent" points="0,0 0,0 0,0 0,0 0,0"/>
    </g>
    </g>
    </svg>
    `,
    diamond: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- diamond -->
    <g id="node1" class="node">
    <title>diamond</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="27,-36 0,-18 27,0 54,-18 27,-36"/>
    </g>
    </g>
    </svg>
    `,
    trapezium: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- trapezium -->
    <g id="node1" class="node">
    <title>trapezium</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="42.7685,-36 11.2315,-36 0,0 54,0 42.7685,-36"/>
    </g>
    </g>
    </svg>
    `,
    parallelogram: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="64pt" height="44pt"
     viewBox="0.00 0.00 63.98 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 59.9847,-40 59.9847,4 -4,4"/>
    <!-- parallelogram -->
    <g id="node1" class="node">
    <title>parallelogram</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="55.977,-36 11.4597,-36 .0077,0 44.525,0 55.977,-36"/>
    </g>
    </g>
    </svg>
    `,
    house: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- house -->
    <g id="node1" class="node">
    <title>house</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-23.5623 27,-36 0,-23.5623 .0252,-3.4377 53.9748,-3.4377 54,-23.5623"/>
    </g>
    </g>
    </svg>
    `,
    pentagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- pentagon -->
    <g id="node1" class="node">
    <title>pentagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-23.5623 27,-36 0,-23.5623 10.3131,-3.4377 43.6869,-3.4377 54,-23.5623"/>
    </g>
    </g>
    </svg>
    `,
    hexagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- hexagon -->
    <g id="node1" class="node">
    <title>hexagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-18 40.5,-36 13.5,-36 0,-18 13.5,0 40.5,0 54,-18"/>
    </g>
    </g>
    </svg>
    `,
    septagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- septagon -->
    <g id="node1" class="node">
    <title>septagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-13.9946 48.6523,-29.2228 27,-36 5.3477,-29.2228 0,-13.9946 14.9839,-1.7826 39.0161,-1.7826 54,-13.9946"/>
    </g>
    </g>
    </svg>
    `,
    octagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- octagon -->
    <g id="node1" class="node">
    <title>octagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-10.5442 54,-25.4558 38.1838,-36 15.8162,-36 0,-25.4558 0,-10.5442 15.8162,0 38.1838,0 54,-10.5442"/>
    </g>
    </g>
    </svg>
    `,
    note: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- note -->
    <g id="node1" class="node">
    <title>note</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="48,-36 0,-36 0,0 54,0 54,-30 48,-36"/>
    <polyline fill="none" stroke="#000000" points="48,-36 48,-30 "/>
    <polyline fill="none" stroke="#000000" points="54,-30 48,-30 "/>
    </g>
    </g>
    </svg>
    `,
    tab: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- tab -->
    <g id="node1" class="node">
    <title>tab</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 12,-36 12,-40 0,-40 0,0 54,0 54,-36"/>
    <polyline fill="none" stroke="#000000" points="0,-36 12,-36 "/>
    </g>
    </g>
    </svg>
    `,
    folder: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- folder -->
    <g id="node1" class="node">
    <title>folder</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 51,-40 30,-40 27,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    box3d: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- box3d -->
    <g id="node1" class="node">
    <title>box3d</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 4,-36 0,-32 0,0 50,0 54,-4 54,-36"/>
    <polyline fill="none" stroke="#000000" points="50,-32 0,-32 "/>
    <polyline fill="none" stroke="#000000" points="50,-32 50,0 "/>
    <polyline fill="none" stroke="#000000" points="50,-32 54,-36 "/>
    </g>
    </g>
    </svg>
    `,
    component: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- component -->
    <g id="node1" class="node">
    <title>component</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 0,-36 0,-32 -4,-32 -4,-28 0,-28 0,-8 -4,-8 -4,-4 0,-4 0,0 54,0 54,-36"/>
    <polyline fill="none" stroke="#000000" points="0,-32 4,-32 4,-28 0,-28 "/>
    <polyline fill="none" stroke="#000000" points="0,-8 4,-8 4,-4 0,-4 "/>
    </g>
    </g>
    </svg>
    `,
    cylinder: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- cylinder -->
    <g id="node1" class="node">
    <title>cylinder</title>
    <path fill="#d3d3d3" stroke="#000000" d="M54,-32.7273C54,-34.5331 41.8982,-36 27,-36 12.1018,-36 0,-34.5331 0,-32.7273 0,-32.7273 0,-3.2727 0,-3.2727 0,-1.4669 12.1018,0 27,0 41.8982,0 54,-1.4669 54,-3.2727 54,-3.2727 54,-32.7273 54,-32.7273"/>
    <path fill="none" stroke="#000000" d="M54,-32.7273C54,-30.9214 41.8982,-29.4545 27,-29.4545 12.1018,-29.4545 0,-30.9214 0,-32.7273"/>
    </g>
    </g>
    </svg>
    `,
    rect: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- rect -->
    <g id="node1" class="node">
    <title>rect</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    rectangle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- rectangle -->
    <g id="node1" class="node">
    <title>rectangle</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    </g>
    </g>
    </svg>
    `,
    square: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="44pt" height="44pt"
     viewBox="0.00 0.00 44.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 40,-40 40,4 -4,4"/>
    <!-- square -->
    <g id="node1" class="node">
    <title>square</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="36,-36 0,-36 0,0 36,0 36,-36"/>
    </g>
    </g>
    </svg>
    `,
    doublecircle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="52pt" height="52pt"
     viewBox="0.00 0.00 52.00 52.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 48)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-48 48,-48 48,4 -4,4"/>
    <!-- doublecircle -->
    <g id="node1" class="node">
    <title>doublecircle</title>
    <ellipse fill="#d3d3d3" stroke="#000000" cx="22" cy="-22" rx="18" ry="18"/>
    <ellipse fill="none" stroke="#000000" cx="22" cy="-22" rx="22" ry="22"/>
    </g>
    </g>
    </svg>
    `,
    doubleoctagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="70pt" height="52pt"
     viewBox="0.00 0.00 70.00 52.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 48)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-48 66,-48 66,4 -4,4"/>
    <!-- doubleoctagon -->
    <g id="node1" class="node">
    <title>doubleoctagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="58,-14.5442 58,-29.4558 42.1838,-40 19.8162,-40 4,-29.4558 4,-14.5442 19.8162,-4 42.1838,-4 58,-14.5442"/>
    <polygon fill="none" stroke="#000000" points="62,-12.4034 62,-31.5966 43.3949,-44 18.6051,-44 0,-31.5966 0,-12.4034 18.6051,0 43.3949,0 62,-12.4034"/>
    </g>
    </g>
    </svg>
    `,
    tripleoctagon: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="78pt" height="60pt"
     viewBox="0.00 0.00 78.00 60.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 56)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-56 74,-56 74,4 -4,4"/>
    <!-- tripleoctagon -->
    <g id="node1" class="node">
    <title>tripleoctagon</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="62,-18.5442 62,-33.4558 46.1838,-44 23.8162,-44 8,-33.4558 8,-18.5442 23.8162,-8 46.1838,-8 62,-18.5442"/>
    <polygon fill="none" stroke="#000000" points="66,-16.4034 66,-35.5966 47.3949,-48 22.6051,-48 4,-35.5966 4,-16.4034 22.6051,-4 47.3949,-4 66,-16.4034"/>
    <polygon fill="none" stroke="#000000" points="70,-14.2627 70,-37.7373 48.606,-52 21.394,-52 0,-37.7373 0,-14.2627 21.394,0 48.606,0 70,-14.2627"/>
    </g>
    </g>
    </svg>
    `,
    invtriangle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- invtriangle -->
    <g id="node1" class="node">
    <title>invtriangle</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="27,0 54,-27 0,-27 27,0"/>
    </g>
    </g>
    </svg>
    `,
    invtrapezium: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- invtrapezium -->
    <g id="node1" class="node">
    <title>invtrapezium</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="11.2315,0 42.7685,0 54,-36 0,-36 11.2315,0"/>
    </g>
    </g>
    </svg>
    `,
    invhouse: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- invhouse -->
    <g id="node1" class="node">
    <title>invhouse</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="0,-12.4377 27,0 54,-12.4377 53.9748,-32.5623 .0252,-32.5623 0,-12.4377"/>
    </g>
    </g>
    </svg>
    `,
    underline: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- underline -->
    <g id="node1" class="node">
    <title>underline</title>
    <polygon fill="#d3d3d3" stroke="transparent" points="54,-36 0,-36 0,0 54,0 54,-36"/>
    <polyline fill="none" stroke="#000000" points="0,0 54,0 "/>
    </g>
    </g>
    </svg>
    `,
    Mdiamond: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- Mdiamond -->
    <g id="node1" class="node">
    <title>Mdiamond</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="27,-36 0,-18 27,0 54,-18 27,-36"/>
    <polyline fill="none" stroke="#000000" points="9,-24 9,-12 "/>
    <polyline fill="none" stroke="#000000" points="18,-6 36,-6 "/>
    <polyline fill="none" stroke="#000000" points="45,-12 45,-24 "/>
    <polyline fill="none" stroke="#000000" points="36,-30 18,-30 "/>
    </g>
    </g>
    </svg>
    `,
    Msquare: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="44pt" height="44pt"
     viewBox="0.00 0.00 44.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 40,-40 40,4 -4,4"/>
    <!-- Msquare -->
    <g id="node1" class="node">
    <title>Msquare</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="36,-36 0,-36 0,0 36,0 36,-36"/>
    <polyline fill="none" stroke="#000000" points="12,-36 0,-24 "/>
    <polyline fill="none" stroke="#000000" points="0,-12 12,0 "/>
    <polyline fill="none" stroke="#000000" points="24,0 36,-12 "/>
    <polyline fill="none" stroke="#000000" points="36,-24 24,-36 "/>
    </g>
    </g>
    </svg>
    `,
    Mcircle: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="44pt" height="44pt"
     viewBox="0.00 0.00 44.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 40,-40 40,4 -4,4"/>
    <!-- Mcircle -->
    <g id="node1" class="node">
    <title>Mcircle</title>
    <ellipse fill="#d3d3d3" stroke="#000000" cx="18" cy="-18" rx="18" ry="18"/>
    <polyline fill="none" stroke="#000000" points="29.9052,-31.5 6.0948,-31.5 "/>
    <polyline fill="none" stroke="#000000" points="29.9052,-4.5 6.0948,-4.5 "/>
    </g>
    </g>
    </svg>
    `,
    promoter: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- promoter -->
    <g id="node1" class="node">
    <title>promoter</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="33.75,-36 13.5,-36 13.5,-18 19.5,-18 19.5,-30 33.75,-30 33.75,-27 45.75,-33 33.75,-39 33.75,-36"/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    cds: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- cds -->
    <g id="node1" class="node">
    <title>cds</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="42,-30 0,-30 0,-6 42,-6 54,-18 42,-30"/>
    </g>
    </g>
    </svg>
    `,
    terminator: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- terminator -->
    <g id="node1" class="node">
    <title>terminator</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="30,-18 30,-24 36,-24 36,-30 18,-30 18,-24 24,-24 24,-18 30,-18"/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    utr: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- utr -->
    <g id="node1" class="node">
    <title>utr</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="36,-18 36,-21 30,-27 24,-27 18,-21 18,-18 36,-18"/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    insulator: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- insulator -->
    <g id="node1" class="node">
    <title>insulator</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="33,-24 33,-12 21,-12 21,-24 33,-24"/>
    <polyline fill="none" stroke="#000000" points="36,-27 36,-9 18,-9 18,-27 36,-27 "/>
    <polyline fill="none" stroke="#000000" points="36,-18 54,-18 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 18,-18 "/>
    </g>
    </g>
    </svg>
    `,
    ribosite: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- ribosite -->
    <g id="node1" class="node">
    <title>ribosite</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="30,-24 30,-25.5 28.5,-27 30,-28.5 30,-30 28.5,-30 27,-28.5 25.5,-30 24,-30 24,-28.5 25.5,-27 24,-25.5 24,-24 25.5,-24 27,-25.5 28.5,-24 30,-24"/>
    <polyline fill="none" stroke="#000000" points="27,-18 27,-19.5 "/>
    <polyline fill="none" stroke="#000000" points="27,-21 27,-22.5 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    rnastab: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- rnastab -->
    <g id="node1" class="node">
    <title>rnastab</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="28.5,-24 30,-25.5 30,-28.5 28.5,-30 25.5,-30 24,-28.5 24,-25.5 25.5,-24 28.5,-24"/>
    <polyline fill="none" stroke="#000000" points="27,-18 27,-19.5 "/>
    <polyline fill="none" stroke="#000000" points="27,-21 27,-22.5 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    proteasesite: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- proteasesite -->
    <g id="node1" class="node">
    <title>proteasesite</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="30,-24 30,-25.5 28.5,-27 30,-28.5 30,-30 28.5,-30 27,-28.5 25.5,-30 24,-30 24,-28.5 25.5,-27 24,-25.5 24,-24 25.5,-24 27,-25.5 28.5,-24 30,-24"/>
    <polyline fill="none" stroke="#000000" points="27,-25.5 27,-18 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    proteinstab: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- proteinstab -->
    <g id="node1" class="node">
    <title>proteinstab</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="28.5,-24 30,-25.5 30,-28.5 28.5,-30 25.5,-30 24,-28.5 24,-25.5 25.5,-24 28.5,-24"/>
    <polyline fill="none" stroke="#000000" points="27,-24 27,-18 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    primersite: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- primersite -->
    <g id="node1" class="node">
    <title>primersite</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="39,-21 27,-33 27,-27 13.5,-27 13.5,-21 39,-21"/>
    <polyline fill="none" stroke="#000000" points="0,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    restrictionsite: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- restrictionsite -->
    <g id="node1" class="node">
    <title>restrictionsite</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="39.75,-21 20.25,-21 20.25,-27 14.25,-27 14.25,-15 33.75,-15 33.75,-9 39.75,-9 39.75,-21"/>
    <polyline fill="none" stroke="#000000" points="0,-18 14.25,-18 "/>
    <polyline fill="none" stroke="#000000" points="39.75,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    fivepoverhang: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- fivepoverhang -->
    <g id="node1" class="node">
    <title>fivepoverhang</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="0,-19.5 24,-19.5 24,-25.5 0,-25.5 0,-19.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="12,-10.5 24,-10.5 24,-16.5 12,-16.5 12,-10.5"/>
    <polyline fill="none" stroke="#000000" points="24,-18 54,-18 "/>
    </g>
    </g>
    </svg>
    `,
    threepoverhang: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- threepoverhang -->
    <g id="node1" class="node">
    <title>threepoverhang</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-19.5 54,-25.5 30,-25.5 30,-19.5 54,-19.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="42,-10.5 42,-16.5 30,-16.5 30,-10.5 42,-10.5"/>
    <polyline fill="none" stroke="#000000" points="0,-18 30,-18 "/>
    </g>
    </g>
    </svg>
    `,
    noverhang: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- noverhang -->
    <g id="node1" class="node">
    <title>noverhang</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="13.5,-19.5 25.5,-19.5 25.5,-25.5 13.5,-25.5 13.5,-19.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="13.5,-10.5 25.5,-10.5 25.5,-16.5 13.5,-16.5 13.5,-10.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="28.5,-10.5 40.5,-10.5 40.5,-16.5 28.5,-16.5 28.5,-10.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="28.5,-19.5 40.5,-19.5 40.5,-25.5 28.5,-25.5 28.5,-19.5"/>
    <polyline fill="none" stroke="#000000" points="40.5,-18 54,-18 "/>
    <polyline fill="none" stroke="#000000" points="13.5,-18 0,-18 "/>
    </g>
    </g>
    </svg>
    `,
    assembly: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- assembly -->
    <g id="node1" class="node">
    <title>assembly</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="15,-19.5 39,-19.5 39,-25.5 15,-25.5 15,-19.5"/>
    <polygon fill="#d3d3d3" stroke="#000000" points="15,-10.5 39,-10.5 39,-16.5 15,-16.5 15,-10.5"/>
    <polyline fill="none" stroke="#000000" points="39,-18 54,-18 "/>
    <polyline fill="none" stroke="#000000" points="0,-18 15,-18 "/>
    </g>
    </g>
    </svg>
    `,
    signature: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- signature -->
    <g id="node1" class="node">
    <title>signature</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-30 0,-30 0,-6 54,-6 54,-30"/>
    <polyline fill="none" stroke="#000000" points="3,-19.5 6,-16.5 "/>
    <polyline fill="none" stroke="#000000" points="3,-16.5 6,-19.5 "/>
    <polyline fill="none" stroke="#000000" points="3,-9 51,-9 "/>
    </g>
    </g>
    </svg>
    `,
    rpromoter: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- rpromoter -->
    <g id="node1" class="node">
    <title>rpromoter</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="36,-30 0,-30 0,0 18,0 18,-6 36,-6 36,0 54,-18 36,-36 36,-30"/>
    </g>
    </g>
    </svg>
    `,
    larrow: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- larrow -->
    <g id="node1" class="node">
    <title>larrow</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-30 18,-30 18,-36 0,-18 18,0 18,-6 54,-6 54,-30"/>
    </g>
    </g>
    </svg>
    `,
    rarrow: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- rarrow -->
    <g id="node1" class="node">
    <title>rarrow</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="36,-30 0,-30 0,-6 36,-6 36,0 54,-18 36,-36 36,-30"/>
    </g>
    </g>
    </svg>
    `,
    lpromoter: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- lpromoter -->
    <g id="node1" class="node">
    <title>lpromoter</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-30 18,-30 18,-36 0,-18 18,0 18,-6 36,-6 36,0 54,0 54,-30"/>
    </g>
    </g>
    </svg>
    `,
    record: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="45pt"
     viewBox="0.00 0.00 62.00 45.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 41)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-41 58,-41 58,4 -4,4"/>
    <!-- record -->
    <g id="node1" class="node">
    <title>record</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="0,-.5 0,-36.5 54,-36.5 54,-.5 0,-.5"/>
    <text text-anchor="middle" x="26.75" y="-14.3" font-family="Times,serif" font-size="14.00" fill="#000000"> </text>
    </g>
    </g>
    </svg>
    `,
    Mrecord: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="45pt"
     viewBox="0.00 0.00 62.00 45.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 41)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-41 58,-41 58,4 -4,4"/>
    <!-- Mrecord -->
    <g id="node1" class="node">
    <title>Mrecord</title>
    <path fill="#d3d3d3" stroke="#000000" d="M12,-.5C12,-.5 42,-.5 42,-.5 48,-.5 54,-6.5 54,-12.5 54,-12.5 54,-24.5 54,-24.5 54,-30.5 48,-36.5 42,-36.5 42,-36.5 12,-36.5 12,-36.5 6,-36.5 0,-30.5 0,-24.5 0,-24.5 0,-12.5 0,-12.5 0,-6.5 6,-.5 12,-.5"/>
    <text text-anchor="middle" x="26.75" y="-14.3" font-family="Times,serif" font-size="14.00" fill="#000000"> </text>
    </g>
    </g>
    </svg>
    `,
    star: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="59pt"
     viewBox="0.00 0.00 62.00 59.36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 55.3571)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-55.3571 58,-55.3571 58,4 -4,4"/>
    <!-- star -->
    <g id="node1" class="node">
    <title>star</title>
    <polygon fill="#d3d3d3" stroke="#000000" points="54,-31.7828 33.3738,-31.7828 27,-51.5368 20.6262,-31.7828 0,-31.7828 16.6869,-19.5742 10.3131,.1798 27,-12.0289 43.6869,.1798 37.3131,-19.5742 54,-31.7828"/>
    </g>
    </g>
    </svg>
    `,
    '(default)': `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
     "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <!-- Generated by graphviz version 2.40.1 (20161225.0304)
     -->
    <!-- Pages: 1 -->
    <svg width="62pt" height="44pt"
     viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
    <polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
    <!-- (default) -->
    <g id="node1" class="node">
    <title>(default)</title>
    <ellipse fill="#ffffff" stroke="#000000" stroke-dasharray="5,2" cx="27" cy="-18" rx="27" ry="18"/>
    </g>
    </g>
    </svg>
    `,
    };
    
    export {shapes};